### ISSUE TITLE
Does not fail on missing required field

### ISSUE THREAD

**Issue by Lakitna** [oaijs/ajv-oai#4]
When you specify a property as required, but omit it from the JSON it will not fail the validation. It should always fail on a missing required property.

## Example

```yaml
# Partial OpenAPI Schema
type: object
required:
  - foo
properties:
  foo:
    type: string
  bar:
    type: string
```

```json
{
  "bar": "some value"
}
```

Validation using this OAS and JSON should fail but doesn't.
